### ISSUE TITLE
Adding a possibility to configure max.poll.records for GCS connector in the UI

### ISSUE THREAD

**Issue by IvanIschenko** [aiven/aiven-kafka-connect-gcs#27]
Hi @ivanyu,
Could you please add a support for manual configuration `max.poll.records` in the GCS connector configuration page?

**Comment by ivanyu** [comment]
Hi!
`max.poll.records` is a setting for the Connect worker, so it doesn't concern the connector itself.
It's being added to Aiven platform soon.
