### ISSUE TITLE
Use templating on the prefix

### ISSUE THREAD

**Issue by wonko** [aiven/aiven-kafka-connect-gcs#29]
For clarity, we would like to use templating on the prefix as well, so the structure on the bucket can be determined by the partition, ...

Would this be feasible?

**Comment by krgn** [comment]
This would be a great feature indeed! Timestamp support would also be great.

**Comment by ivanyu** [comment]
Hi,

We are considering deprecating prefixes altogether.
`file.name.template` can contain any prefix by itself, including `/` separators. And in there you can already use templating.
