### ISSUE TITLE
Use Json value and transforms

### ISSUE THREAD

**Issue by paperboatinrain** [aiven/aiven-kafka-connect-gcs#35]
Currently the connector expects the value converter to always be ByteArrayConverter.
This makes it difficult to use transforms that expect a Struct type. 

Is it possible to use Json Converter or somehow allow transforms that expect a Struct type?

**Comment by paperboatinrain** [comment]
@ivanyu  am i missing something or is this not possible at this time?

**Comment by ivanyu** [comment]
@paperboatinrain you're right, such limitation does exist: it's not possible to use other converters at this point. However, currently we're reworking how the data is processed and written in the connector. JSON and other formats will be surely supported.
