### ISSUE TITLE
[Feature request] specific naming pattern for created files

### ISSUE THREAD

**Issue by IvanIschenko** [aiven/aiven-kafka-connect-gcs#8]
Hi guys, thanks for your work!
I have two questions:
1. I am currently using Kafka GCS sink connector, and I am wondering can I somehow configure my specific naming pattern for created files (for example to take some value from the event).
2. Also, I am interested can I configure a write process of only one record per file in Kafka GCS sink connector.

**Comment by ivanyu** [comment]
@IvanIschenko for 2, I created a separate issue (#9) and start working on it.

**Comment by ivanyu** [comment]
@IvanIschenko about 1, could you please give an example of the naming pattern you would like to have?

**Comment by IvanIschenko** [comment]
Currently, we are using `<prefix><topic>-<partition>-<start-offset>[.gz]` pattern for files. 
Can we use key values from the message in Kafka topic (so I can paste in theory any value there)?

**Comment by ivanyu** [comment]
@IvanIschenko FYI: #19

**Comment by IvanIschenko** [comment]
I will close this task because of #19 task.
